### ISSUE TITLE
Transfer the repository ownership

### ISSUE THREAD

**Issue by ludofleury** [project-satisfy/satisfy#178]
Hello @ramunasd 

It's long overdue, but you are the core contributor keeping this repository alive for the community.
I'd like to thank you first for taking over and also transfer you the ownership :)

**Comment by ramunasd** [comment]
Thanks @ludofleury , i'm doing my best :)
If You have decided to handover this project to someone then I would be happy to take that responsibility.

**Comment by ludofleury** [comment]
I sent the transfer request, the repository is now officially in your hands. It was about time for you to get the credit you deserved. I'm really happy to witness the magic of open source at work. 

All the best to you fellow engineer :)
