### ISSUE TITLE
Webhook 500 Response Code 255

### ISSUE THREAD

**Issue by createdwithlove** [project-satisfy/satisfy#184]
I know the 500 error message is very non-specific, but I'm hoping someone else has a clue that points in the right direction.

We run a self-hosted gitlab and have set up Satis Gitlab (https://github.com/mborne/satis-gitlab) to update the satis.json, which is then used by satisfy to update the packages every 5 minutes via cron.  So far so good - the system has been running quite smoothly for years.

But now we wanted to have a look at the webhooks, because that sounds much more reasonable. 

We set up the webhook in a gitlab repository and made the access token available in paramaters.yml. 
Unfortunately, an error 500 always comes back now and we have no clue what that could be caused by.

![Bildschirmfoto 2023-07-10 um 15 31 38](https://github.com/project-satisfy/satisfy/assets/1146811/4f473b66-7bc9-4e11-87c0-d0b3aaea0456)

With a wrong token a "Invalid Token (400 Bad Request)" comes back - so the hook at least arrives at Satisfy. Playing around and testing the request with curl we always get an  400 Bad Request – Cannot find specified repository.

Any ideas?

**Comment by ramunasd** [comment]
Closed as stale.
