### ISSUE TITLE
How to set up a user for the backend

### ISSUE THREAD

**Issue by abcpremium** [project-satisfy/satisfy#194]
Hey,

I installed the package as requested, however I have an issue with the user. When installing, it asks me for a username. But it didn't ask for a password. And also, when trying to access the backend then, I get an exception, that admin.users expects an array, but a string is given. I worked around this by modifying my parameters.yml like this:

```
parameters:
    ...
    admin.auth: true
    admin.users:
        [name: admin]
    ...
```

However, how do I set a password? Thanks in  advance!

**Comment by ramunasd** [comment]
PLease refer to config for test env - https://github.com/project-satisfy/satisfy/blob/main/config/config_testsecure.yml
